# yamllint disable rule:line-length
---
version: 2
jobs:
  rubocop:
    working_directory: ~/homebrew-tools
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - run:
          name: Install RuboCop
          command: gem install rubocop --version 0.78.0
      - run:
          name: Run RuboCop
          command: rubocop
  shellcheck:
    working_directory: ~/homebrew-tools
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: shellcheck Bin/*
  yamllint:
    working_directory: ~/homebrew-tools
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Update permissions (/usr/local/bin)
          command: sudo chown -R circleci:circleci /usr/local/bin
      - run:
          name: Update permissions (/usr/local/lib)
          command: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: python-deps-{{ .Branch }}
      - run:
          name: Install YAML Linter
          command: sudo pip install --quiet yamllint
      - run:
          name: Run YAML Linter
          command: yamllint .
      - save_cache:
          key: python-deps-{{ .Branch }}
          paths:
            - /usr/local/bin
            - /usr/local/lib/python3.8/site-packages
workflows:
  version: 2
  checks:
    jobs:
      - rubocop
      - shellcheck
      - yamllint
# yamllint enable
