# yamllint disable rule:line-length

name: Update formulae

on:
  # Trigger every hour to check formulae referencing other repositories
  schedule:
    - cron: "0 * * * *"

  # Trigger on command source file changes
  push:
    branches:
      - main
    paths:
      - Bin/*

  # Allow manually triggering this workflow
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Update formulae
        id: update-formulae
        run: echo "::set-output name=changes::$(Scripts/update-formulae | sed -r 's/^/- /')"

      - name: Create or update pull-request
        id: create-pull-request-action
        uses: peter-evans/create-pull-request@v3
        with:
          branch: workflows/update-formulae
          delete-branch: true
          commit-message: |
            Update formulae

            ${{ steps.update-formulae.outputs.changes }}
          title: Update formulae
          body: |
            Updates to the formulae in this repository

            ${{ steps.update-formulae.outputs.changes }}

            Auto-generated by the [update-formulae][1] workflow

            [1]: https://github.com/pmeinhardt/homebrew-tools/blob/main/.github/workflows/update-formulae.yml
          reviewers: pmeinhardt
          labels: automated pull request

      - name: Print pull-request details
        run: echo "${{ steps.create-pull-request-action.outputs.pull-request-operation }} ${{ steps.create-pull-request-action.outputs.pull-request-url }}"
